project11_jinja_tags_spc_url_map/app1/urls.py
from django.urls import path

from app1.views import *

app_name='app1'

urlpatterns=[
    path('students/',students,name='students')
]

project11_jinja_tags_spc_url_map/app2/urls.py
from django.urls import path

from app2.views import *

app_name='app2'

urlpatterns=[
    path('It/',It,name='It')
]

project11_jinja_tags_spc_url_map/project11_jinja_tags_spc_url_map/urls.py
from django.contrib import admin
from django.urls import path,include
from app3.views import *
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    path('task/',task,name='task'),
]

project11_jinja_tags_spc_url_map/app1/views.py
from django.shortcuts import render

# Create your views here.

def students(request):
    return render(request,'students.html')

project11_jinja_tags_spc_url_map/app2/views.py
from django.shortcuts import render

# Create your views here.

def It(request):
    return render(request,'It.html')

project11_jinja_tags_spc_url_map/app3/views.py
from django.shortcuts import render

# Create your views here.
def task(request):
    return render(request,'task.html')

project11_jinja_tags_spc_url_map/templates/It.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>It</title>
</head>
<body>
    <center>
        <h1>MNC companies</h1>
        <h2>Amazon</h2>
        <a href=" {% url 'task' %} "><h1>Register here...!</h1></a>
    </center>
</body>
</html>

project11_jinja_tags_spc_url_map/templates/students.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Students</title>
</head>
<body>
    <center>
        <h1>All students gather here.... war begins </h1>
        <a href="{% url 'app2:It' %}"><h1>succfully you register</h1></a>
    </center>
</body>
</html>

project11_jinja_tags_spc_url_map/templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Fill your details</h1>
        <a href="{% url 'app1:students' %}"><h1>submit</h1></a>
    </center>
</body>
</html>